[package]
name = "win32u_sym"
version = "0.1.0"
authors = ["Chris Martin <marti4d@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
